version: '3.8'

services:
  kineto:
    image: 
    container_name: kineto
    ports:
      - "8080:8080"
    
    environment:
      KINETO_URL: "gemini://[YOUR CAPSULE]"
      KINETO_BIND: "0.0.0.0:8080"
      #KINETO_CSS_FILE: "/app/style.css"
      #KINETO_CSS_URL: ""
      KINETO_DISABLE_PROXY: "false"
    #volumes:
    #   - ./style.css:/app/style.css
    restart: unless-stopped
